CONF_CURTAIN_SPEED = "curtain_speed"
DEFAULT_CURTAIN_SPEED = 255

CURTAIN3_SPEED_QUIETDRIFT = "quietdrift"
CURTAIN3_SPEED_SILENT = "silent"
CURTAIN3_SPEED_NORMAL = "normal"

CURTAIN3_SPEED_TO_MODE = {
    CURTAIN3_SPEED_QUIETDRIFT: 1,
    CURTAIN3_SPEED_SILENT: 2,
    CURTAIN3_SPEED_NORMAL: 255,
}

ROLLER_SHADE_SPEED_PERFORMANCE = "performance"
ROLLER_SHADE_SPEED_QUIET = "quiet"

ROLLER_SHADE_SPEED_TO_MODE = {
    ROLLER_SHADE_SPEED_PERFORMANCE: 0,
    ROLLER_SHADE_SPEED_QUIET: 1,
}
